CREATE TABLE languages
(
    code    VARCHAR(255) NOT NULL,
    name    VARCHAR(64)  NOT NULL,
    endonym VARCHAR(64)  NOT NULL,
    CONSTRAINT pk_languages PRIMARY KEY (code)
);

CREATE TABLE collections
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id              VARCHAR(64)                             NOT NULL,
    collection_id        VARCHAR(64)                             NOT NULL,
    created              TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    title                VARCHAR(64)                             NOT NULL,
    source_language_code VARCHAR(255),
    target_language_code VARCHAR(255),
    CONSTRAINT pk_collections PRIMARY KEY (id)
);

ALTER TABLE collections
    ADD CONSTRAINT uc_collections_collection UNIQUE (collection_id);

ALTER TABLE collections
    ADD CONSTRAINT FK_COLLECTIONS_ON_SOURCE_LANGUAGE_CODE FOREIGN KEY (source_language_code) REFERENCES languages (code);

ALTER TABLE collections
    ADD CONSTRAINT FK_COLLECTIONS_ON_TARGET_LANGUAGE_CODE FOREIGN KEY (target_language_code) REFERENCES languages (code);

CREATE TABLE collection_entries
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    parent_id BIGINT,
    keyword   VARCHAR(128)                            NOT NULL,
    CONSTRAINT pk_collection_entries PRIMARY KEY (id)
);

CREATE TABLE translations
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    collection_entry_id BIGINT                                  NOT NULL,
    translation_value   VARCHAR(128)                            NOT NULL,
    CONSTRAINT pk_translations PRIMARY KEY (id)
);

ALTER TABLE translations
    ADD CONSTRAINT FK_TRANSLATIONS_ON_COLLECTION_ENTRY FOREIGN KEY (collection_entry_id) REFERENCES collection_entries (id);

INSERT INTO languages (code, name, endonym)
VALUES ('af', 'Afrikaans', 'Afrikaans'),
       ('am', 'Amharic', 'አማርኛ'),
       ('ar', 'Arabic', 'العربية'),
       ('az', 'Azerbaijani', 'Azərbaycan dili'),
       ('be', 'Belarusian', 'Беларуская мова'),
       ('bg', 'Bulgarian', 'Български'),
       ('bn', 'Bengali', 'বাংলা'),
       ('bs', 'Bosnian', 'Bosanski jezik'),
       ('ca', 'Catalan', 'Català'),
       ('co', 'Corsican', 'Corsu'),
       ('cs', 'Czech', 'Čeština'),
       ('cy', 'Welsh', 'Cymraeg'),
       ('da', 'Danish', 'Dansk'),
       ('de', 'German', 'Deutsch'),
       ('el', 'Greek', 'Ελληνικά'),
       ('en', 'English', 'English'),
       ('eo', 'Esperanto', 'Esperanto'),
       ('es', 'Spanish', 'Español'),
       ('et', 'Estonian', 'Eesti'),
       ('eu', 'Basque', 'Euskara'),
       ('fa', 'Persian', 'فارسی'),
       ('fi', 'Finnish', 'Suomi'),
       ('fr', 'French', 'Français'),
       ('ga', 'Irish', 'Gaeilge'),
       ('gd', 'Scots Gaelic', 'Gàidhlig'),
       ('gl', 'Galician', 'Galego'),
       ('gu', 'Gujarati', 'ગુજરાતી'),
       ('ha', 'Hausa', 'هَوُسَ'),
       ('he', 'Hebrew', 'עִבְרִית'),
       ('hi', 'Hindi', 'हिन्दी'),
       ('hr', 'Croatian', 'Hrvatski'),
       ('ht', 'Haitian Creole', 'Kreyòl ayisyen'),
       ('hu', 'Hungarian', 'Magyar'),
       ('hy', 'Armenian', 'Հայերեն'),
       ('id', 'Indonesian', 'Bahasa Indonesia'),
       ('ig', 'Igbo', 'Asụsụ Igbo'),
       ('is', 'Icelandic', 'Íslenska'),
       ('it', 'Italian', 'Italiano'),
       ('ja', 'Japanese', '日本語'),
       ('jv', 'Javanese', 'Basa Jawa'),
       ('ka', 'Georgian', 'ქართული'),
       ('kk', 'Kazakh', 'Қазақ тілі'),
       ('km', 'Khmer', 'ភាសាខ្មែរ'),
       ('kn', 'Kannada', 'ಕನ್ನಡ'),
       ('ko', 'Korean', '한국어'),
       ('ku', 'Kurdish', 'Kurdî'),
       ('ky', 'Kyrgyz', 'Кыргызча'),
       ('la', 'Latin', 'Latina'),
       ('lb', 'Luxembourgish', 'Lëtzebuergesch'),
       ('lo', 'Lao', 'ພາສາລາວ'),
       ('lt', 'Lithuanian', 'Lietuvių kalba'),
       ('lv', 'Latvian', 'Latviešu valoda'),
       ('mg', 'Malagasy', 'Malagasy'),
       ('mi', 'Maori', 'Te Reo Māori'),
       ('mk', 'Macedonian', 'Македонски јазик'),
       ('ml', 'Malayalam', 'മലയാളം'),
       ('mn', 'Mongolian', 'Монгол хэл'),
       ('mr', 'Marathi', 'मराठी'),
       ('ms', 'Malay', 'Bahasa Melayu'),
       ('mt', 'Maltese', 'Malti'),
       ('my', 'Myanmar', 'ဗမာစာ'),
       ('ne', 'Nepali', 'नेपाली'),
       ('nl', 'Dutch', 'Nederlands'),
       ('no', 'Norwegian', 'Norsk'),
       ('ny', 'Nyanja', 'ChiCheŵa'),
       ('or', 'Odia', 'ଓଡ଼ିଆ'),
       ('pa', 'Punjabi', 'ਪੰਜਾਬੀ'),
       ('pl', 'Polish', 'Polski'),
       ('ps', 'Pashto', 'پښتو'),
       ('pt', 'Portuguese', 'Português'),
       ('ro', 'Romanian', 'Română'),
       ('ru', 'Russian', 'Русский'),
       ('rw', 'Kinyarwanda', 'Ikinyarwanda'),
       ('sd', 'Sindhi', 'سنڌي'),
       ('si', 'Sinhala', 'සිංහල'),
       ('sk', 'Slovak', 'Slovenčina'),
       ('sl', 'Slovenian', 'Slovenščina'),
       ('sm', 'Samoan', 'Gagana Samoa'),
       ('sn', 'Shona', 'ChiShona'),
       ('so', 'Somali', 'Soomaali'),
       ('sq', 'Albanian', 'Shqip'),
       ('sr', 'Serbian', 'Српски језик'),
       ('st', 'Sesotho', 'Sesotho'),
       ('su', 'Sundanese', 'Basa Sunda'),
       ('sv', 'Swedish', 'Svenska'),
       ('sw', 'Swahili', 'Kiswahili'),
       ('ta', 'Tamil', 'தமிழ்'),
       ('te', 'Telugu', 'తెలుగు'),
       ('tg', 'Tajik', 'Тоҷикӣ'),
       ('th', 'Thai', 'ไทย'),
       ('tk', 'Turkmen', 'Türkmençe'),
       ('tl', 'Tagalog', 'Wikang Tagalog'),
       ('tr', 'Turkish', 'Türkçe'),
       ('tt', 'Tatar', 'Татарча'),
       ('ug', 'Uyghur', 'ئۇيغۇرچە'),
       ('uk', 'Ukrainian', 'Українська'),
       ('ur', 'Urdu', 'اردو'),
       ('uz', 'Uzbek', 'Oʻzbekcha'),
       ('vi', 'Vietnamese', 'Tiếng Việt'),
       ('xh', 'Xhosa', 'isiXhosa'),
       ('yi', 'Yiddish', 'ייִדיש'),
       ('yo', 'Yoruba', 'Yorùbá'),
       ('zh', 'Chinese', '中文'),
       ('zu', 'Zulu', 'isiZulu');
